Orange-OpenSource/hurl

.travis.yml
src/parser/xml.rs
src/runner/predicate.rs
src/runner/template.rs
src/runner/value.rs

Fix new clippy warning match-like-matches-macro

Update to rust 1.47.0

---

packages/hurl/src/jsonpath/parser/reader.rs
packages/hurl/src/main.rs
packages/hurl/src/runner/http_response.rs
packages/hurl/src/runner/log_deserialize.rs
packages/hurl_core/src/parser/reader.rs
packages/hurl_core/src/parser/sections.rs
packages/hurl_core/src/parser/string.rs
packages/hurlfmt/src/linter/rules.rs

fix new clippy warnings:
- inconsistent_struct_constructor
- manual_map
- copied

Update to Rust 1.52

---

packages/hurl/src/http/client.rs
packages/hurl/src/http/mod.rs
packages/hurl/src/http/request.rs
packages/hurl/src/main.rs
packages/hurl/src/runner/body.rs
packages/hurl/src/runner/hurl_file.rs
packages/hurl/src/runner/log_deserialize.rs
packages/hurl/src/runner/log_serialize.rs
packages/hurl/src/runner/request.rs
packages/hurl/src/runner/response.rs
packages/hurl/tests/libcurl.rs
packages/hurl/tests/runner.rs

Refacto http client

---

ci/dependency_age.sh

Use short options instead of long options for macOS compatibility:
- `sed --in-place` => `sed -i " "`
- `sed --silent` => `sed -n`
- `tr --delete`=> `tr -d`

Use short option for macOS compatibility.

---

.github/workflows/release.yml
.github/workflows/test.yml

This PR to rename "osx" occurrences to "macos"

Rename osx to macos in GitHub actions files.

---

.gitignore
contrib/npm/README.md
contrib/npm/archive.js
contrib/npm/bin.js
contrib/npm/docs/hurl.1
contrib/npm/docs/hurlfmt.1
contrib/npm/hurl.js
contrib/npm/hurlfmt.js
contrib/npm/install.js
contrib/npm/package-lock.json
contrib/npm/package.json
contrib/npm/platform.json

Add Hurl installation with npm:
```
$ cd contrib/npm
$ npm install
```
The PR is still in draft, as I've not tested it on Windows / Linux.

Install Hurl with npm.

---

packages/hurl/src/cli/options.rs

Also add a function doc, use a reference for argument and make function private.

Remove useless logs.

---

integration/test_hurl.py
integration/tests_ok/follow_redirect.py
packages/hurl/src/http/core.rs

Fix redirection not followed

---

integration/ssl/error_self_signed_certificate.linux-fedora.err
integration/test_hurl.py
packages/hurl/tests/libcurl.rs

On with openssl 3.0.0, some messages have been changed.
For this test, I think this PR has updated our expected value: https://github.com/openssl/openssl/commit/ade08735f9d0ac85d611c5abee8a1df651bbca13#diff-1c0b5127081224cb77ee0fb3e3032c48227c476fca67312ae8c19efea9813e38R61

Fix certificate test message.

---

integration/ad_hoc.sh
packages/hurl/src/main.rs

Fix broken stdin.

---

packages/hurl/src/cli/mod.rs
packages/hurl/src/util/logger.rs

Make error more colorfull.

---

bin/install_prerequisites_archlinux.sh

Add glibc dependency to ArchLinux prerequisites.

---

Cargo.lock
bin/install_prerequisites_alpine.sh
bin/install_prerequisites_archlinux.sh
packages/hurl/Cargo.toml

Patches chrono 0.4.20 regression on ArchLinux / Alpine docker image.

---

packages/hurl/src/cli/options.rs
packages/hurl/src/main.rs
packages/hurl/src/util/logger.rs

Display deprecated warning when using --progress and --summary option.

---

Cargo.lock
bin/install_prerequisites_alpine.sh
bin/install_prerequisites_archlinux.sh
packages/hurl/Cargo.toml

Fix regression https://github.com/chronotope/chrono/issues/755

Fix regression in chrono 0.4.20 https://github.com/chronotope/chrono/issues/755

---

packages/hurl/src/cli/interactive.rs
packages/hurl/src/main.rs
packages/hurl/src/runner/core.rs
packages/hurl/src/runner/hurl_file.rs
packages/hurl/tests/runner.rs

Make pre_entry and post_entry optional to remove clone on each entry when not interactive.

---

packages/hurl/src/runner/entry.rs
packages/hurl/src/util/logger.rs

Add color on capture in verbose mode.

---

packages/hurl/src/cli/options.rs

Parsing number options can be done with clap api leading to less code in Hurl with better message:
Range:
```
error: Invalid value "0" for '--to-entry <ENTRY_NUMBER>': 0 is not in 1..=4294967295
error: Invalid value "-4" for '--max-redirs <NUM>': -4 is not in -1..=2147483647
```
Default value:
```
--connect-timeout <SECONDS>         Maximum time allowed for connection [default: 300]
````

Simplify option parsing using clap apis.

---

CHANGELOG.md
bin/check/changelog.sh
bin/release/get_release_note.py
integration/ad_hoc.sh
packages/hurlfmt/src/main.rs

Fix hurlfmt --color crash

---

bin/check/changelog.sh
bin/release/get_release_note.py
bin/release/get_release_note.test.py
bin/requirements-frozen.txt
bin/requirements.txt

lxml.HTMLParser is having troubled with emoji content https://github.com/Orange-OpenSource/hurl/issues/959. Besides, BeautifulSoup is already a dependance for our tests suite.
Fix #959.

Replace lxml.HTMLParser with BeautifulSoup parser

---

CHANGELOG.md
integration/tests_ok/resolve.curl
integration/tests_ok/resolve.hurl
integration/tests_ok/resolve.options
integration/tests_ok/resolve.out
packages/hurl/src/cli/options.rs
packages/hurl/src/http/client.rs
packages/hurl/src/http/options.rs
packages/hurl/src/runner/entry.rs
packages/hurl/src/runner/runner_options.rs

Add --resolve option

---

.gitignore
bin/test/test_prerequisites.ps1
bin/test/test_prerequisites.sh

Move *.log file generated during integrations tests from `integration` to `integration/build`.

Move *.log to build/

---

packages/hurl/src/http/client.rs
packages/hurl/tests/libcurl.rs

Delete `redirect_count`.
Make `handle private.

Clean HTTP client fields.

---

.github/workflows/package.yml
.github/workflows/test.yml

See https://github.com/actions/runner-images/pull/7125 and https://github.com/actions/runner-images/issues/7128

Patch GitHub macOS build.

---

packages/hurl/src/cli/options/duration.rs
packages/hurl/src/cli/options/matches.rs
packages/hurl/src/runner/assert.rs
packages/hurl/src/runner/filter/eval.rs
packages/hurl/src/runner/filter/nth.rs
packages/hurl/src/runner/options.rs
packages/hurl/src/runner/predicate.rs
packages/hurl/src/runner/predicate_value.rs
packages/hurl_core/src/ast/core.rs
packages/hurl_core/src/format/html.rs
packages/hurl_core/src/parser/duration.rs
packages/hurl_core/src/parser/number.rs
packages/hurl_core/src/parser/option.rs
packages/hurl_core/src/parser/predicate.rs
packages/hurl_core/src/parser/predicate_value.rs
packages/hurl_core/src/parser/sections.rs
packages/hurl_core/src/typing.rs
packages/hurlfmt/src/format/json.rs
packages/hurlfmt/src/format/token.rs
packages/hurlfmt/src/linter/rules.rs

in order to preserve user input

Wrap primitives within struct
