Orange-OpenSource/hurl

src/linter/rules.rs
src/runner/assert.rs
src/runner/body.rs
src/runner/capture.rs
src/runner/entry.rs
src/runner/expr.rs
src/runner/json.rs
src/runner/multipart.rs
src/runner/predicate.rs
src/runner/query.rs
src/runner/request.rs
src/runner/response.rs
src/runner/template.rs

Typically all the eval functions on the AST struct
so that eval and ast can live in 2 different crates
Defining a trait makes sense only if the signature is always the same,
which is not the case for eval function.

Refacto - Remove inherent impl

---

.github/workflows/rust.yml
README.md

release for both Linux and OSX

Update github actions

---

packages/hurl/src/main.rs

The argument should match https://github.com/Orange-OpenSource/hurl/blob/master/packages/hurl/src/main.rs#L376

Fix cookies_input_file argument name mismatch

---

integration/server.py

It might solve the import issue with the form_param.py test
ImportError: cannot import name 'attach_enctype_error_multidict' from partially initialized module 'flask.debughelpers' (most likely due to a circular import) (/usr/local/lib/python3.9/site-packages/flask/debughelpers.py)

Do not run flask in debug mode anymore

---

README.md

Can be regenerated easily with https://raw.githubusercontent.com/ekalinin/github-markdown-toc/master/gh-md-toc.

Add toc to readme.

---

packages/hurl/src/cli/fs.rs
packages/hurl/src/cli/mod.rs
packages/hurl/src/cli/variables.rs
packages/hurl/src/http/client.rs
packages/hurl/src/main.rs
packages/hurl/src/runner/content_decoding.rs
packages/hurl/src/runner/core.rs
packages/hurl/src/runner/entry.rs
packages/hurl/src/runner/error.rs
packages/hurl/src/runner/query.rs
packages/hurl/src/runner/xpath.rs
packages/hurl/tests/libcurl.rs
packages/hurl_core/src/parser/template.rs
packages/hurlfmt/src/cli/fs.rs
packages/hurlfmt/src/cli/mod.rs
packages/hurlfmt/src/format/json.rs
packages/hurlfmt/src/format/token.rs

- upper_case_acronyms
- redundant_slicing
- vec_init_then_push

Fix new clippy warnings (Rust 1.51)

---

packages/hurl/src/runner/xpath.rs

This type will be either i8 or u8, depending on the architecture

Using type definition std::os::raw::c_char

---

Cargo.lock
packages/hurl/Cargo.toml
packages/hurl/src/cli/mod.rs
packages/hurl/src/cli/options.rs
packages/hurl/src/main.rs
packages/hurl/src/report/junit.rs
packages/hurl/src/report/mod.rs

Hello.
This PR provides basic support for writing JUnit XML report files, which is a common format for aggregating test results that's supported by many CI tools (Jenkins, Gitlab, etc).
I thought this would be useful to have as I'd like to use this in CI with prettier reporting (that hooks into other workflows too).
**Examples**
```bash
❯ echo 'GET https://google.com/' | ./target/debug/hurl --junit google.xml
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>301 Moved</TITLE></HEAD><BODY>
<H1>301 Moved</H1>
The document has moved
<A HREF="https://www.google.com/">here</A>.
</BODY></HTML>
atc in dennis in hurl on  junit-xml-report [?] via 🦀 v1.56.0 via ❄️  impure (nix-shell) via 🐏 7GiB/23GiB
❯ cat google.xml
1   │ <?xml version="1.0"?>
2   │ <testsuites …
```

Basic JUnix XML report support

---

.github/workflows/test.yml

Cargo test multithread runner might pose a problem to our libxml based implementation.
On Windows, but also on macOs, we can have random segmentation fault:
```
Caused by:
568
process didn't exit successfully: `D:\a\hurl\hurl\target\debug\deps\hurl-33f8d88a0d2b2f3c.exe` (exit code: 0xc0000005, STATUS_ACCESS_VIOLATION)
```
So, we temporarily switch to a single threaded execution for `cargo test` and will revert as soon as we've fixed this issue.

Run cargo test in single thread 

---

ci/windows/hurl.nsi

Solves complaints in the https://github.com/microsoft/winget-pkgs repository, and complaints from other people about the DisplayName being too long in Control Panel as the Application Name is being truncated due to how long it is.
Almost all applications have a DisplayName that isn't too long, i.e. `Microsoft OneDrive`; `Microsoft Teams`, etc.
This change was also done to make it a bit more consistent with other programs.
Related: https://github.com/texstudio-org/texstudio/pull/2000

Fixes the DisplayName being too long.

---

packages/hurl/src/report/mod.rs
packages/hurl/src/report/report.css

Add tiny cosmetic improvement to html report (us can be closed without merging):
Before:
After:

Add tiny css improvments to html export.

---

packages/hurl/src/cli/fs.rs
packages/hurl/src/http/request_spec.rs
packages/hurl/src/http/version.rs
packages/hurl/src/main.rs
packages/hurl/src/report/junit/testcase.rs
packages/hurl/src/runner/error.rs
packages/hurl/src/runner/predicate.rs
packages/hurl_core/src/ast/display.rs
packages/hurl_core/src/ast/json.rs
packages/hurl_core/src/format/html.rs
packages/hurlfmt/src/format/json.rs
packages/hurlfmt/src/main.rs

Mainly unnecessary calls to to_string on types that implements Display traits <https://rust-lang.github.io/rust-clippy/master/index.html#to_string_in_format_args>.

Fix new clippy warnings on 1.58.

---

packages/hurl/src/http/client.rs
packages/hurl/src/http/core.rs
packages/hurl/src/http/response.rs

Change function signature from
```rust 
pub fn get_header_values(headers: Vec<Header>, expected_name: String) -> Vec<String> {
```
to 
```rust 
pub fn get_header_values(headers: &[Header], expected_name: &str) -> Vec<String> {
```
(no need to transfer ownership)

Use slices parameter in get_header_values.

---

integration/report.sh
integration/ssl/cacert.options
integration/test_hurl.py
integration/tests/basic_authentication.options
integration/tests/cookie_file.options
integration/tests/error_body_json.options
integration/tests/error_connect_timeout.options
integration/tests/error_max_redirect.options
integration/tests/error_timeout.options
integration/tests/post_json.options
integration/tests/proxy.options
integration/tests/variables.options

This allows us to use options value with space in integration tests.

Use new line for splitting options.

---

.circleci/config.yml
.github/workflows/test.yml
integration/test_hurl.py
integration/tests/multipart_form_data.windows.curl
integration/tests/post_file.windows.curl
packages/hurl/src/http/client.rs
packages/hurl/src/http/options.rs
packages/hurl/src/http/request_spec.rs
packages/hurl/src/main.rs
packages/hurl/src/runner/body.rs
packages/hurl/src/runner/core.rs
packages/hurl/src/runner/entry.rs
packages/hurl/src/runner/hurl_file.rs
packages/hurl/src/runner/multipart.rs
packages/hurl/src/runner/request.rs
packages/hurl/src/runner/response.rs
packages/hurl/tests/libcurl.rs
packages/hurl/tests/runner.rs

We use `PathBuf` in `ClientOptions` and in `RunnerOptions`;  an `&Path` in functions if possible.

Use Path/PathBuf struct when appropriates.

---

docs/hurl.md
packages/hurl/src/cli/options.rs

Remove deprecated `--html` option (replace by `--report-html`).

Delete deprecated html report options.

---

packages/hurl/src/http/request_spec.rs
packages/hurl_core/src/format/html.rs

Mainly https://rust-lang.github.io/rust-clippy/master/index.html#single_char_pattern.

Fix clippy 1.59 warnings.

---

ci/build_and_test.sh

current curl issue
https://github.com/curl/curl/issues/8559
Reproducible in a docker container
```
curl 'https://localhost:8001/hello' --cacert ssl/cert.pem
curl: (27) Out of memory
```

Skip Tests on Archlinux

---

integration/test_hurl.py

When we check the curl commands of a given Hurl file, the current check output, when in error, is 
```
Assert error at tests_ok/assert_xpath.err
expected: 1 commands
actual:   4 commands
```
This PR fixes with this message:
```
curl commands error at tests_ok/assert_xpath.curl
expected: 1 commands
actual:   4 commands
```

Fix curl command check error output.

---

packages/hurl/tests/libcurl.rs

PR split out from #506. On Monterey, I've observed that the library returns 28, causing these assertions to fail. However, in GH actions with the macos-latest environment, 7 is returned which passes. This change just asserts more generally for known exit codes and error messages across platforms, since it didn't seem the rest of the app was dependent on the specific error code/message.

Generalize tests for curl timeout error codes

---

.github/workflows/test.yml
ci/build_and_test.sh

Test build are done with --release and --locked.
Hurl and curl version are outputed just after build.
Ex on [Ubuntu](https://github.com/Orange-OpenSource/hurl/runs/5632708092?check_suite_focus=true
):
```
hurl 1.7.0-snapshot libcurl/7.68.0 OpenSSL/1.1.1f zlib/1.2.11 brotli/1.0.3840 libidn2/2.2.0 libssh/0.9.3/openssl/zlib 1.40.0
curl 7.68.0 (x86_64-pc-linux-gnu) libcurl/7.68.0 OpenSSL/1.1.1f zlib/1.2.11 brotli/1.0.7 libidn2/2.2.0 libpsl/0.21.0 
```
Hurl uses libcurl 7.68.0 (while curl crate has a static version of libcurl/7.81.0)
On macOS GitHub image:
```
hurl 1.7.0-snapshot libcurl/7.64.1 (SecureTransport) LibreSSL/2.8.3 zlib/1.2.11
curl 7.82.0 (x86_64-apple-darwin20.6.0) libcurl/7.82.0 (SecureTransport) OpenSSL/1.1.1m zlib/1.2.11 brotli/1.0.9 zstd/1.5.2 libidn2/2.3.2 libssh2/1.10.0 …
```

Uniform Hurl build on test CI.

---

packages/hurl/tests/libcurl.rs

This test can be used to reproduced a bug related to libcurl
independently of Hurl.

Add test for debugging

---

packages/hurl/src/http/version.rs

This PR add some missing prefix for Hurl version output.
Before this PR:
```
$ hurl --version
hurl 1.6.1 libcurl/7.77.0 (SecureTransport) LibreSSL/2.8.3 zlib/1.2.11 1.42.0
```
After this PR:
```
$ hurl --version
hurl 1.7.0-snapshot libcurl/7.77.0 (SecureTransport) LibreSSL/2.8.3 zlib/1.2.11 nghttp2/1.42.0
```

Add missing prefix for Hurl version output.

---

contrib/vim/README.md
contrib/vim/ftdetect/hurl.vim
contrib/vim/syntax/hurl.vim
contrib/vim/test.hurl

This is a first basic version to get syntax highlighting in VIM.
VIM Syntax highlighting is flexible but quite complicated. 
This first version needs to be improved in order to deal with more edge cases.
A sample Hurl file is given in order to show the current capability of the syntax highlighting.

Add basic Syntax highlighting for VIM

---

packages/hurl/src/http/client.rs
packages/hurl/src/http/content_decoding.rs
packages/hurl/src/http/error.rs
packages/hurl/src/http/mod.rs
packages/hurl/src/main.rs
packages/hurl/src/runner/entry.rs
packages/hurl/src/runner/error.rs
packages/hurl/src/runner/http_response.rs
packages/hurl/src/runner/query.rs
packages/hurl/src/runner/response.rs
packages/hurl/tests/libcurl.rs

This PR has two commits:
- first commit : use HttpError instead of RunnerError in http package
- second commit : move encoding, is_html, text functions from runner/http_response to http/content_decoding. 
In a following PR, we may split functions in http/content_decoding

Clean http package error code

---

bin/crates_update.sh

sed -i "" "foo" instead of sed -i "foo"

Fix crates_update.sh to be supported on macOS.

---

Cargo.lock
packages/hurl/Cargo.toml

As suggested in https://github.com/rusqlite/rusqlite/pull/1031/files.

Use minimal chrono features (to remove potential CVE in time crate)

---

packages/hurl/src/cli/options.rs
packages/hurl/src/http/client.rs
packages/hurl/src/http/mod.rs
packages/hurl/src/http/options.rs
packages/hurl/src/main.rs
packages/hurl/src/runner/core.rs
packages/hurl/src/runner/entry.rs
packages/hurl/src/runner/hurl_file.rs
packages/hurl/tests/runner.rs

When very-verbose is used, the HTTP body response is logged.
For instance, this Hurl file:
```
GET https://google.fr
GET https://www.google.fr
```
Then:
```
$ hurl --very-verbose --no-output google.hurl
* Options:
*     fail fast: true
*     insecure: false
*     follow redirect: false
*     max redirect: 50
* ------------------------------------------------------------------------------
* Executing entry 1
*
* Cookie store:
*
* Request:
* GET https://google.fr
*
* Request can be run with the following curl command:
* curl 'https://google.fr'
*
> GET / HTTP/2
> Host: google.fr
> accept: */*
> user-agent: hurl/1.7.0-snapshot
>
< HTTP/2 301
< location: https://www.google.fr/
< content-type: text/html; charset=UTF-8
< date: Fri, 17 Jun 2022 16:33:29 GMT
< expires: Fri, 17 Jun 2022 16:33:29 …
```

Add very verbose option

---

docs/spec/README
docs/spec/generate_html.sh
docs/spec/style.css

Add script to validate grammar and generate HTML.
The next step is to customize the CSS so that the HTML can be added in the doc.

Validate Grammar and generate HTML

---

packages/hurl/src/http/client.rs
packages/hurl/src/http/core.rs
packages/hurl/src/http/header.rs
packages/hurl/src/http/mod.rs
packages/hurl/src/http/request.rs
packages/hurl/src/http/request_spec.rs
packages/hurl/src/http/response.rs
packages/hurl/src/http/response_cookie.rs
packages/hurl/src/runner/query.rs
packages/hurl/src/runner/response.rs
packages/hurl/tests/libcurl.rs

This PR:
- create a http::header mod in hurl package
- move Header struct from http::core to http::headers
~~- create header utils function in http::headers_util~~
- all call using headers can use `RequestSpec::get_header_values` ~~and `Response::get_header_value`~~
The rational behind this:
In a following PR, I will need to use request headers in order to print request body. We will be able to implement `Request::get_header_values`. 
~~To discuss: when calling `header_util::get_values` vs `get_values`?~~

Create http::header module.

---

ci/build_and_test.sh

Following https://github.com/curl/curl/issues/8559 fix, ArchLinux tests should be ok now.

Reactivate ArchLinux integration tests.

---

.github/workflows/test.yml
integration/ad_hoc.sh
packages/hurl/src/main.rs

I have added another script `ad_hoc.sh` to add tests that can not be easily added in `tests_ok/` and `tests_failed/`.
It could also include the test for multiple hurl files.

Improve "File not found" error message

---

packages/hurl/src/cli/options.rs

Use multiple_values method instead of deprecated multiple_occurences method.
Closes #652.

Fix multiple input files support

---

integration/tests_ok/color.err
packages/hurl/src/cli/mod.rs
packages/hurl/src/http/client.rs
packages/hurl/src/http/debug.rs
packages/hurl/src/http/request_debug.rs
packages/hurl/src/http/response_debug.rs
packages/hurl/src/json/result.rs
packages/hurl/src/main.rs
packages/hurl/src/report/junit/testcase.rs
packages/hurl/src/runner/entry.rs
packages/hurl/src/runner/hurl_file.rs
packages/hurl/src/util/logger.rs
packages/hurl/src/util/mod.rs
packages/hurl/tests/libcurl.rs
packages/hurl/tests/runner.rs
packages/hurl_core/src/format/html.rs

This PR to make some modifications about the way we log.
In function signature:
Before:
```rust
pub fn run(
hurl_file: HurlFile,
http_client: &mut http::Client,
filename: &str,
options: &RunnerOptions,
log_verbose: &impl Fn(&str),
log_error_message: &impl Fn(bool, &str),
log_error: &impl Fn(&Error, bool),
) -> HurlResult {
```
After:
```rust
pub fn run(
hurl_file: HurlFile,
lines: &Vec<&str>,
filename: &str,
http_client: &mut http::Client,
options: &RunnerOptions,
logger: &Logger,
) -> HurlResult {
```
There was no clear differences between `log_error_message`, `log_error` etc... and some duplications on logger codes. Now, user must provides a logger struct.
In the code, when we want to log:
Before:
```rust
log_verbose("");
log_verbose("Cookie store:");
for cookie in …
```

Rationalize log functions usages.

---

integration/tests_ok/color.err
packages/hurl/src/cli/mod.rs
packages/hurl/src/json/result.rs
packages/hurl/src/main.rs
packages/hurl/src/report/junit/testcase.rs
packages/hurl/src/runner/hurl_file.rs
packages/hurl/src/util/logger.rs
packages/hurl/tests/libcurl.rs
packages/hurl/tests/runner.rs

This PR crates 2 loggers:
- a basic logger (info, debug, error) for basic error (file not here etc...)
- a dedicated Hurl logger for a file (info, debug, error + error_rich to display beautiful parser / runtime error string)

Clean logger

---

integration/tests_ok/color.err
integration/tests_ok/verbose.err.pattern
integration/tests_ok/very_verbose.err.pattern
packages/hurl/src/http/client.rs
packages/hurl/src/http/debug.rs
packages/hurl/src/http/request_debug.rs
packages/hurl/src/http/response_debug.rs
packages/hurl/src/main.rs
packages/hurl/src/runner/entry.rs
packages/hurl/src/util/logger.rs

With `--very-verbose`:
Before:
After:
Compared to `httpie`:

Make verbose and very-verbose logs more colored.

---

packages/hurl/src/cli/options.rs

Support NO_COLOR env variable (https://no-color.org)

---

packages/hurl/src/http/client.rs
packages/hurl/src/main.rs
packages/hurl/src/runner/entry.rs
packages/hurl/src/runner/hurl_file.rs
packages/hurl/tests/libcurl.rs
packages/hurl/tests/runner.rs

This is a preliminary PR for #624 .
`ClientOptions` is not saved  anymore in `Client` struct. We pass now an `option: &ClientOptions` parameter in each method of the HTTP client. This will make easier to override a `ClientOption` for each executed request.

Pass client_options in execute and executes_with_redirect HTTP client methods

---

integration/tests_ok/option_verbose.err.pattern
integration/tests_ok/verbose.err.pattern
integration/tests_ok/very_verbose.err.pattern
packages/hurl/src/http/client.rs

In verbose mode, log the number of bytes received and duration (the HTTP response header Content-Length is not mandatory) so it's always useful to have the number of bytes received.
The logs looks like:
```
* Executing entry 1
*
* Cookie store:
*
* Request:
* GET http://localhost:8000/verbose
*
* Request can be run with the following curl command:
* curl 'http://localhost:8000/verbose'
*
> GET /verbose HTTP/1.1
> Host: localhost:8000
> Accept: */*
> User-Agent: hurl/~~~
>
* Response: (received 12 bytes in 10 ms)
*
< HTTP/1.0 200 OK
< Content-Type: text/html; charset=utf-8
< Content-Length: 12
< Server: Flask Server
< Date: ~~~
<
*
```

Log number bytes received and duration.

---

integration/tests_ok/test.err.pattern
packages/hurl/src/main.rs
packages/hurl/src/util/logger.rs

Improve text summary:
```shell
$ hurl --test *.hurl
test/bar.hurl: Running [1/3]
test/bar.hurl: Success (5 request(s) in 136 ms)
test/baz.hurl: Running [2/3]
error: Assert failure
--> test/baz.hurl:6:0
|
6 | xpath "string(//title)" == "Something"
|   actual:   string <301 Moved>
|   expected: string <Something>
|
test/baz.hurl: Failure (4 request(s) in 62 ms)
test/foo.hurl: Running [3/3]
test/foo.hurl: Success (10 request(s) in 527 ms)
--------------------------------------------------------------------------------
Executed files:  3
Succeeded files: 2 (66.7%)
Failed files:    1 (33.3%)
Duration:        766 ms
```
Fixes #593 
Fixes #779

Improve text summary.

---

packages/hurl/src/http/client.rs
packages/hurl/src/main.rs
packages/hurl/src/runner/core.rs
packages/hurl/src/runner/entry.rs
packages/hurl/src/runner/hurl_file.rs
packages/hurl/src/runner/mod.rs
packages/hurl/tests/libcurl.rs
packages/hurl/tests/runner.rs

Currently, the entry is run with 2  options structs:  `RunnerOptions` and `ClientOptions`.
The `ClientOptions` can be overriden in the `[Options]` section.
This PR is about using only the `RunnerOptions` struct when running a hurl_file or an entry.
It contains all the options (including all the HTTP options) and can be overriden by the [Options] section in the Hurl file.
(the `ClientOptions` will only be used when making the HTTP call)
Remarks:
The `[Options]` section currently only belongs to an entry, but in the future, we could have such a section globally for the full Hurl file.
We should be able to use the same `RunnerOptions` struct.
Variables have also been removed from The `RunnerOptions` struct.client constructor.

Use only the RunnerOptions struct when running a Hurl File/Entry

---

Cargo.toml
bin/release/release.sh

Set `[profile.release]` flag to reduce Hurl binary size.
Options that affect size have been chosen (and not performance).
On a Mac, the binary size goes from 5.7M to 3.2M.
Source:
- [Make your Rust Binaries TINY!](https://www.youtube.com/watch?v=b2qe3L4BX-Y)
- https://github.com/johnthagen/min-sized-rust/blob/master/Cargo.toml
To note: the build time in release can be slightly bigger( we can see with this PR how the build time is affected).

Reduces Hurl release binary size.

---

packages/hurl/src/http/version.rs
packages/hurl/src/main.rs

Before:
```shell
$ hurl --version
hurl 1.7.0 libcurl/7.77.0 (SecureTransport) LibreSSL/2.8.3 zlib/1.2.11 nghttp2/1.42.0
```
After:
```shell
$ hurl --version
hurl 1.7.0 libcurl/7.77.0 (SecureTransport) LibreSSL/2.8.3 zlib/1.2.11 nghttp2/1.42.0
Features (libcurl):  alt-svc AsynchDNS HSTS HTTP2 IPv6 Largefile libz NTLM NTLM_WB SPNEGO SSL UnixSockets
Features (built-in): brotli
```
Some features are not available from crates `curl-rust`:
```
CURL_VERSION_GSSAPI        (1<<17)
CURL_VERSION_KERBEROS5     (1<<18)
CURL_VERSION_PSL           (1<<20)
CURL_VERSION_HTTPS_PROXY   (1<<21)
CURL_VERSION_MULTI_SSL     (1<<22)
CURL_VERSION_THREADSAFE    (1<<30)
```
See https://github.com/alexcrichton/curl-rust/issues/464
Closes #836.

List all libcurl features with `--version`

---

contrib/vim/syntax/hurl.vim

Not the best, but better than the current, it uses proper highlight definition links instead of hardcoded colors, so themes work better.

Improve vim hurl syntax

---

packages/hurl/src/jsonpath/parser/combinators.rs
packages/hurl/src/jsonpath/parser/parse.rs
packages/hurl_core/src/parser/bytes.rs
packages/hurl_core/src/parser/combinators.rs
packages/hurl_core/src/parser/filter.rs
packages/hurl_core/src/parser/json.rs
packages/hurl_core/src/parser/predicate.rs
packages/hurl_core/src/parser/predicate_value.rs
packages/hurl_core/src/parser/query.rs
packages/hurl_core/src/parser/sections.rs

With a slice as argument, we can use a vec or an array. In Hurl code, we use choice with array only. We also change the implementation to remove the recursive call (and unncessary clone)

Change choice parser function signature to take a slice as argument.

---

packages/hurl/src/cli/options.rs
packages/hurl/src/http/client.rs
packages/hurl/src/http/options.rs
packages/hurl/src/main.rs
packages/hurl/src/runner/entry.rs
packages/hurl/src/runner/runner_options.rs
packages/hurl_core/src/ast/core.rs
packages/hurl_core/src/format/html.rs
packages/hurl_core/src/parser/sections.rs
packages/hurlfmt/src/format/token.rs

Hi there 👋 ,
Thanks for creating Hurl and open sourcing it, it's really neat!
I noticed that to fully support mTLS, the `--cert` and `--key` cli flags were not yet supported.
This PR adds support for configuring the client cert and private key for establishing a mutual TLS connection to a server.
Example:
```
GET https://localhost:8443/
[Options]
cacert: out/HurlCA.crt
client_cert: out/client.crt
client_key: out/client.key
HTTP 200
```
outputs:
```
Request can be run with the following curl command:
* curl 'https://localhost:8443/' --cacert out/HurlCA.crt --cert out/client.crt --key out/client.key
```
This is my first Rust PR, so I probably got a few things wrong. There's a decent amount of duplication that could probably be simplified.
Naming wise, I've used `client_cert` and …

Add client cert/key to command line args and options

---

README.md

Update project description to indicate how to install Hurd on FreeBSD

Hurl is now available on FreeBSD

---

packages/hurl/src/runner/capture.rs
packages/hurl/src/runner/filter.rs
packages/hurl/src/runner/json.rs
packages/hurl/src/runner/predicate.rs
packages/hurl/src/runner/query.rs
packages/hurl/src/runner/request.rs
packages/hurl/tests/runner.rs
packages/hurl_core/src/ast/core.rs
packages/hurl_core/src/ast/display.rs
packages/hurl_core/src/ast/json.rs
packages/hurl_core/src/format/html.rs
packages/hurl_core/src/parser/bytes.rs
packages/hurl_core/src/parser/cookiepath.rs
packages/hurl_core/src/parser/json.rs
packages/hurl_core/src/parser/multiline.rs
packages/hurl_core/src/parser/parsers.rs
packages/hurl_core/src/parser/predicate.rs
packages/hurl_core/src/parser/primitives.rs
packages/hurl_core/src/parser/query.rs
packages/hurl_core/src/parser/sections.rs
packages/hurl_core/src/parser/string.rs
packages/hurl_core/src/parser/url.rs
packages/hurlfmt/src/format/json.rs
packages/hurlfmt/src/format/text.rs
packages/hurlfmt/src/format/token.rs
packages/hurlfmt/tests/json.rs

We're changing the `Template` AST struct from:
```rust
pub struct Template {
pub quotes: bool,
pub elements: Vec<TemplateElement>,
pub source_info: SourceInfo,
}
```
to 
```rust
pub struct Template {
pub delimiter: Option<char>,
pub elements: Vec<TemplateElement>,
pub source_info: SourceInfo,
}
```
In order to facilitate incoming changes on one line string (body `` `foo` ``)

Change Template struct using delimiter: Option char field instead of quotes: bool.

---

docs/installation.md

Hurl has a dependency on libxml2 on Debian/Ubuntu. This package isn't automatically installed in a fresh Debian/Ubuntu docker container, and results in a broken installation experience.
```
docker run -ti debian:11-slim bash
export HURL_VERSION=1.8.0
apt update && apt install -y curl jq ca-certificates
curl -LO "https://github.com/Orange-OpenSource/hurl/releases/download/${HURL_VERSION}/hurl_${HURL_VERSION}_amd64.deb"
dpkg -i "hurl_${HURL_VERSION}_amd64.deb"
Selecting previously unselected package hurl.
(Reading database ... 7120 files and directories currently installed.)
Preparing to unpack hurl_1.8.0_amd64.deb ...
Unpacking hurl (1.8.0) ...
dpkg: dependency problems prevent configuration of hurl:
hurl depends on libxml2; however:
Package libxml2 is not installed.
dpkg: error processing …
```

Docs: Use apt to install the local Debian/Ubuntu package to resolve dependencies

---

CONTRIBUTING.md

Signing a commit can mean "signed off" or "signed with a GPG key". This PR updates the contributing docs, refines the wording and adds the GH documentation URL that usually pops up after the PR has been created.

Update commit signing docs in Contributing guide

---

Cargo.lock
docs/spec/hurl.grammar
packages/hurl/Cargo.toml
packages/hurl_core/src/parser/string.rs
packages/hurlfmt/Cargo.toml

in #1045, we aligned the parser implementation for the key-string with the grammar using a blacklist pattern `~[#:\n\\]+`
It turns out to be not very robust as it can now accept one-line JSON such as `{"id":1}`.
We will therefore come back to a whitelist pattern.
`(alphanum | "_" | "-" | "." | "[" | "]" | "@" | "$") +`

Fix key-string parser

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_proposal.md

Context: I created a few issues and reviewed existing issues, and did some repetitive work to add everything that is helpful. I'm used to following a guided structure in the form of an issue template but do not really like the GitHub-provided defaults. 
This PR includes the following issue templates as a first iteration:
- Bug report
- Feature proposal (intentionally proposal instead of request - everyone can contribute)
The templates are inspired by https://gitlab.com/gitlab-org/gitlab/-/tree/master/.gitlab/issue_templates

Add issue templates: Bug report, feature proposal

---

docs/templates.md

The docs have the wrong parameter in the example

Fix variables-file example

---

Cargo.lock
packages/hurl/Cargo.toml
packages/hurl/src/report/html/mod.rs
packages/hurl/src/report/html/testcase.rs
packages/hurl/src/util/path.rs

Use an uuid as identifier for the HTML Hurl file run report

---

packages/hurl/src/http/certificate.rs
packages/hurl/src/http/client.rs
packages/hurl/src/http/easy_ext.rs
packages/hurl/src/http/mod.rs
packages/hurl/src/json/result.rs
packages/hurl/tests/libcurl.rs

```
$ hurl <<<"GET https://hurl.dev" --json | jq '.entries|.[0].calls|.[0].response.certificate'
{
"expire_date": "2023-04-29 10:44:12 UTC",
"issue": "C = US, O = Let's Encrypt, CN = R3",
"serial_number": "03dbc4f3c85e1366cc52a3692cfa04a07bb1",
"start_date": "2023-01-29 10:44:13 UTC",
"subject": "CN = hurl.dev"
}
```
Remarks:
The cert_info strings can be different in Linux/Mac and windows:
- attribute name: `Start date` vs `Start Date`
- issuer:  `C = US, ST = Denial, L = Springfield, O = Dis, CN = localhost` vs `C=US, ST=Denial, L=Springfield, O=Dis, CN=localhost`
- serial number:  `1ee8b17f1b64d8d6b3de870103d2a4f533535ab0` vs `1e:e8:b1:7f:1b:64:d8:d6:b3:de:87:01:03:d2:a4:f5:33:53:5a:b0:`
- date format: `Jan 10 08:29:52 2023 GMT" vs "2023-01-10 08:29:52 GMT`

Add certificate in HTTP response

---

docs/tutorial/security.md

While reading through the documentation, I found two typing mistakes in the HTML attributes.

Fix HTML attribute typo

---

docs/spec/hurl.grammar
integration/ssl/insecure.curl
integration/ssl/insecure.hurl
packages/hurl/src/runner/query.rs
packages/hurl_core/src/ast/core.rs
packages/hurl_core/src/format/html.rs
packages/hurl_core/src/parser/query.rs
packages/hurlfmt/src/format/json.rs
packages/hurlfmt/src/format/token.rs
packages/hurlfmt/src/linter/rules.rs

```
GET https://localhost:8001/hello
HTTP 200
[Asserts]
certificate "Subject" == "C=US, ST=Denial, L=Springfield, O=Dis, CN=localhost"
certificate "Issuer" == "C=US, ST=Denial, L=Springfield, O=Dis, CN=localhost"
certificate "Start-Date" format "%Y-%M-%d %H:%m:%S UTC" == "2023-29-10 08:01:52 UTC"
certificate "Expire-Date" format "%Y-%M-%d %H:%m:%S UTC" == "2025-29-30 08:10:52 UTC"
certificate "Serial-Number" == "1e:e8:b1:7f:1b:64:d8:d6:b3:de:87:01:03:d2:a4:f5:33:53:5a:b0"
`Hello World!`
```
The asserts on the certificate are independent of the HTTPS connection.
We can access an HTTPS  endpoint with an invalid certificate using an insecure connection (`--insecure /-k`) and still be able to check the certificate attributes.

Add certificate query

---

packages/hurl_core/src/ast/json.rs

@fabricereix in <https://github.com/Orange-OpenSource/hurl/blob/master/packages/hurl_core/src/ast/json.rs> I've struggled to see the difference between `fmt::Display::fmt` on `Value` (the `to_string`method) and the `encoded` method:
https://github.com/Orange-OpenSource/hurl/blob/2472aa90e9ebbc82780ba014e764b7a58ecb9469/packages/hurl_core/src/ast/json.rs#L77-L78
vs
https://github.com/Orange-OpenSource/hurl/blob/2472aa90e9ebbc82780ba014e764b7a58ecb9469/packages/hurl_core/src/ast/json.rs#L137
We need to improve function docs!
Maybe one method is not useful, (see also the coverage on this file => <https://orange-opensource.github.io/hurl/coverage/packages/hurl_core/src/ast/json.rs.html>

Remove dead method on `json::Value`.

---

integration/hurl/tests_failed/assert_query_cookie.err
integration/hurl/tests_failed/assert_query_cookie.hurl
packages/hurl/src/runner/predicate.rs
packages/hurl/src/runner/value.rs

There is only one behavior change relating to the unit type.
We can now include it in the equality.
For example.
```
cookie "cookie[Secure]" not == true
```
The query `cookie "cookie[Secure]"` return a Unit, that will always be different from the bool true.

Use Value equality in == and != predicates

---

packages/hurlfmt/src/curl/mod.rs

This PR improves the parse function to properly handle Chrome-style cURL commands, which use `\` for line continuation. Previously, the function failed with a "Can not parse curl command at line X: Invalid escape" error when encountering `\`.
Fix details:
* Removes escaped newlines (`\n` and `\r\n`) after `\` to merge multi-line cURL commands into a single line.
* Adds new test cases to cover Chrome-style cURL input.

fix invalid escape in hurlfmt parse func
